package backend.utils;

import backend.domain.ScannedItem;
import javafx.collections.ObservableList;

import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Date;

import javax.imageio.ImageIO;

/**
 * Saves a receipt of a purchase to /Downloads/ folder
 */
public class ReceieptHandler {

    public static void printReceipt(ObservableList<ScannedItem> currentSale, double totalsum) throws IOException {

        int width = 700;
        int height = 1000;

        // Constructs a BufferedImage of one of the predefined image types.
        BufferedImage bufferedImage = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);

        // Create a graphics which can be used to draw into the buffered image
        Graphics2D g2d = bufferedImage.createGraphics();

        // fill all the image with white
        g2d.setColor(Color.white);
        g2d.fillRect(0, 0, width, height);

        g2d.setColor(Color.BLACK);
        g2d.setFont(new Font("Courier", Font.ITALIC, 20));
        g2d.drawString("THE RECEIPT", 320, 100);


        g2d.drawString("Thank you for shopping with us :)", 250, 150);

        g2d.drawString("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", 65, 200);

        g2d.drawString("Product name:", 75, 230);
        g2d.drawString("Product quantity:", 320, 230);
        g2d.drawString("Product price:", 550, 230);

        int y = 230;

        //prints the shopping cart data on the receipt
        for ( ScannedItem scannedItem : currentSale ){
            y = y + 50;
            g2d.drawString( scannedItem.getItemName(),75, y );
            g2d.drawString(String.valueOf(scannedItem.getItemQuantity()) ,320, y );
            g2d.drawString(Double.toString(Double.parseDouble(DecimalHandler.format(scannedItem.getItemPrice()))) + " €", 550, y );
        }

        y = y + 100;
        g2d.drawString("Total sum: " + DecimalHandler.format(totalsum) + " €",450, y );

        //Adds cashiers name on the receipt
        /* y = y +100;
        g2d.drawString( "Receipt generated by: " + System.getProperty("user.name"), 25, y );*/

        //Adds the date+time on the receipt
        g2d.drawString("" + new Date(),25, y );

        g2d.dispose();

        // Save as PNG
        String home = System.getProperty("user.home");
        File filePNG = new File(home+"/Downloads/" + "receipt.png");
        ImageIO.write(bufferedImage, "png", filePNG);


        //Save as JPEG
       /*File fileJPEG = new File(home+"/Downloads/" + "receipt.jpg");
        ImageIO.write(bufferedImage, "jpg", fileJPEG);
        */
    }
}
